### PR TITLE
adding GIFs for VSCode Marketplace listing

### PR DESCRIPTION
**Pull request by ayim**
Changes:
- Added two GIFs to be shown in the VSCode Marketplace listing (https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode-completions)

### CODE REVIEW

**Comment by ayim** [comment]
@gewarren @ghogen, is there a more formal process for adding/linking to GIFs from a VSCode Marketplace listing?

**Comment by ghogen** [comment]
@ayim
I don't know where you should upload these, but I would suggest that this isn't the best place for them. We have a tool that we sometimes use that deletes unused image files, where "unused" means not references in a docs page. Can you check with the Marketplace owners to see what they recommend?

**Comment by ayim** [comment]
@ghogen, will do - thanks for the suggestion!

**Comment by markw-t** [comment]
@ayim another choice is to actually use the same images in a relevant docs page for the feature.  For things that aren't yet doc'd JC and others use Github user content from their publish pipelines as a hosting spot (e.g https://user-images.githubusercontent.com/116461/69910156-96274b80-13fe-11ea-9be4-d801f4e9c377.gif is the image for GistPad)

**Pull request merged**
